# Generated by Django 5.2.15 on 2026-06-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('short_description', models.TextField()),
                ('tech_stack', models.CharField(max_length=300)),
                ('github', models.URLField(blank=True)),
                ('live_demo', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
